apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pankaj2
  description: pankaj2description
spec:
  type: openapi
  lifecycle: production
  owner: pankaj2team
  definition: |
    openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /pankaj2:
    get:
      tags:
      - pankaj-2-api
      operationId: pankaj1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}

