apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The petstore API
spec:
  type: openapi
  lifecycle: production
  definition:
    $text: 'https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml'
