name: Generate and Display OpenAPI Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggers

jobs:
  generate-openapi-docs:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 23 (with distribution specified)
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    # Step 3: Change directory to 'pankaj2'
    - name: Change directory to pankaj2
      run: cd Pankaj2

    # Step 4: Run Maven compile
    - name: Run Maven compile
      run: mvn compile -Dskip.enunciate=true

    # Step 5: Access and print JSON file
    - name: Print JSON file content
      run: |
        cat Pankaj2/target/docs/apidocs/ui/openapi.json
