name: Generate and Display OpenAPI Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggers

jobs:
  generate-openapi-docs:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 23 (with distribution specified)
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'

    # Step 3: Build the Spring Boot application
    - name: Build with Maven
      run: mvn clean package

    # Step 4: Run the Spring Boot application in the background
    - name: Start Spring Boot Application
      run: |
        nohup java -jar Pankaj1/target/*.jar --server.port=8090 &
        sleep 30 # Wait for the app to start

     # Step 4: Run the Spring Boot application in the background
    - name: Start Spring Boot Application
      run: |
        nohup java -jar Pankaj2/target/*.jar --server.port=8091 &
        sleep 30 # Wait for the app to start

    # Step 5: Fetch OpenAPI documentation (assuming it's available at /v3/api-docs)
    - name: Fetch OpenAPI Docs
      run: curl http://localhost:8090/v3/api-docs -o openapi8090.json

    # Step 5: Fetch OpenAPI documentation (assuming it's available at /v3/api-docs)
    - name: Fetch OpenAPI Docs
      run: curl http://localhost:8091/v3/api-docs -o openapi8091.json


    # Step 6: Display OpenAPI Docs in the logs
    - name: Display OpenAPI Docs
      run: cat openapi8090.json

    # Step 6: Display OpenAPI Docs in the logs
    - name: Display OpenAPI Docs
      run: cat openapi8091.json
